# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Building the app"
  lane :build do
    gym(scheme: "Reminders", 
  	project: "Reminders.xcodeproj",
	clean: true,
	skip_codesigning: true,
	xcargs: "-skipMacroValidation -allowProvisioningUpdates",
	# destination: "platform=iOS Simulator,name=iPhone 14,OS=16.0",
	export_method: "development",
	export_team_id: "4JDZ4BJ4PW"
	)
  end
end
